name: CI
on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build static lib
      run: make lib/libanimdata.a

    - name: Build test binary
      run: make bin/test

    - name: Run tests
      run: make test
